apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app.kubernetes.io/instance: nginx
    app.kubernetes.io/name: nginx
  namespace: homework
spec:
  selector:
    app.kubernetes.io/instance: nginx
    app.kubernetes.io/name: nginx
  type: ClusterIP
  ports:
  - port: 9113
    targetPort: exporter
    protocol: TCP
    name: nginx
