apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: sm-nginx
  labels:
    app.kubernetes.io/instance: nginx
    app.kubernetes.io/name: nginx
  namespace: homework
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: nginx
      app.kubernetes.io/name: nginx
  namespaceSelector:
    matchNames: 
      - homework
  endpoints:
  - port: nginx-service
    path: /metrics
    interval: 15s
