---
namespaceOverride: dev
controller:
  replicaCount: 1
image:
  tag: latest
listeners:
  client:
    protocol: PLAINTEXT
  controller:
    protocol: PLAINTEXT
  interbroker:
    protocol: PLAINTEXT
