controller:
  replicaCount: 5
image:
  tag: 3.5.2
listeners:
  client:
    protocol: SASL_PLAINTEXT
  controller:
    protocol: SASL_PLAINTEXT
  interbroker:
    protocol: SASL_PLAINTEXT
namespaceOverride: prod
