apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-webserver
  namespace: homework
spec:
  storageClassName: "sc-homework"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
